outpath:
    LTR-vis-output/

samples:
    cdna_ubc_01 : https://s3.amazonaws.com/nanopore-human-wgs/rna/fastq/UBC_Run1_20170913_1D.pass.dedup.fastq

reference:
    dna.fasta:
        hg38: https://hgdownload.soe.ucsc.edu/goldenPath/hg38/bigZips/hg38.fa.gz
    cdna.fasta:
        hg38: ftp://ftp.ensembl.org/pub/release-98/fasta/homo_sapiens/cdna/Homo_sapiens.GRCh38.cdna.all.fa.gz
    gtf:
        hg38: ftp://ftp.ensembl.org/pub/release-98/gtf/homo_sapiens/Homo_sapiens.GRCh38.98.gtf.gz

mapping_settings:
    dna        : -x splice
    cdna       : -x map-ont
    read-to-gene : --splice -c --secondary=no

genes:
    E2F1   : E2F1
    BRCA1  : BRCA1
    BRCA2  : BRCA2
    PLSCR3 : PLSCR3
    TEST : TEST

exec:
    gene_reads : scripts/get_reads_by_gene.py
    gene       : scripts/get_gene.py
    paf_to_json : scripts/paf_to_json.py
    fastq_to_json : scripts/fastq_to_json.py
    fasta_to_json : scripts/fasta_to_json.py
